---

- name: generate ceph.conf configuration file
    src: "ceph.conf.j2"
    dest: "{{ ceph_conf_key_directory }}/{{ cluster }}.conf"
    owner: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    mode: "0644"
    config_overrides: "{{ ceph_conf_overrides }}"